# Lintのルールは次のリンクを参考にしてね
#   https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

first-line-h1: false
no-hard-tabs: false
no-duplicate-heading: false
line-length:
  line_length: 150
  tables: false
  code_blocks: false
  headings: false
