@startuml

start
:出展者ページへの移動;
fork
    :紹介文編集;
    :更新可否選択;

fork again
    :出展者写真編集;
    :ファイル選択;
    :アップロード可否選択;

fork again
    :作品展示編集;
    :ファイル選択;
    :表示順選択;
    :更新可否;

end fork

stop
@enduml
