@startuml 出展依頼
start
:展示会の企画内容決定;
:パートナー（出展者候補者）に送るメールの内容の決定;
:出展依頼メールを配信;
:出展申し込みを受領;
:ブラックリスト判定;
if(condtion) then(True)
    :出品過多によるお断りメール;
    else(False)
    :作品発送先、期限の案内メール;
endif

stop
@enduml


他の部品として「展示用ホームページ作成」、請求書発行、会計連携
