@startuml 展示準備
start
:作品受領（期限）;

fork
    :展示の枠決め;
    :展示場設定日時を出展者へ連絡;
    :作品の会場への運搬;

fork again
    :広告用ホームページ作成;
    :パトロンへの案内メール作成;
    :パトロンへの案内メール配信;

fork again
    :その他広報活動;

end fork

stop
@enduml
